title: For Fun & Profit
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: foo
favicon: "assets/favicon.png"
logo: "assets/logo.png"

url: https://fahadsultan.com/csc222

aux_links:
  Course Moodle Page: https://courses.furman.edu/course/view.php?id=18041#section-0
  LeetCode: https://leetcode.com
  CCSC:SE: http://ccscse.org/programming_contest/problems/
  Wheel of Misfortune: wheel.html

footer_content: "Copyright &copy; 2024 Syed Fahad Sultan. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

markdown: kramdown
mathjax: true

callouts:
  deadline:
    title: Deadline
    color: red
  warning:
    title: Warning
    color: red
  notice:
    color: yellow
  note:
    title: Note
    color: yellow
  tip:
    color: green
    title: Tip